import json
import urllib.request
import urllib.error
from app.core.config import settings

def explain_setup_with_ollama(setup_details: dict) -> str:
    """
    Calls local Ollama service to generate setup explanation.
    """
    prompt = (
        f"Explain this stock trading setup in plain English:\n"
        f"- Ticker Symbol: {setup_details.get('symbol')}\n"
        f"- Zone Type: {setup_details.get('zone_type')} (Supply/Demand)\n"
        f"- Pattern: {setup_details.get('pattern')}\n"
        f"- Timeframe: {setup_details.get('timeframe')}\n"
        f"- Suggested Entry: Rs {setup_details.get('entry')}\n"
        f"- Stop Loss: Rs {setup_details.get('stop_loss')}\n"
        f"- Target 1: Rs {setup_details.get('target_1')}\n"
        f"- Final Score: {setup_details.get('final_score')}/100\n\n"
        f"Write a short, professional quantitative analysis summary. "
        f"Explain the entry level, risk limits, and score. Keep it concise."
    )
    
    url = f"{settings.OLLAMA_URL}/api/generate"
    data = {
        "model": settings.OLLAMA_MODEL,
        "prompt": prompt,
        "stream": False
    }
    
    req_body = json.dumps(data).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=req_body,
        headers={"Content-Type": "application/json"},
        method="POST"
    )
    
    try:
        # 3 second timeout for responsive client fallback
        with urllib.request.urlopen(req, timeout=3) as response:
            resp_data = json.loads(response.read().decode("utf-8"))
            return resp_data.get("response", "No response text generated by Ollama.")
    except Exception as e:
        # Fallback trigger: raise runtime warning
        raise RuntimeError("Ollama connection failed or timed out.") from e
